[package]
name = "llm_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
langchain-rust = { version = "4.6.0", features = ["postgres", "ollama"] }
serde_json = "1.0.128"
tokio = { version = "1", features = ["full"] }
